#!/usr/bin/env bash

OLD_PS1="$PS1"
OLD_GOPATH="$GOPATH"

deactivate () {
    export GOPATH="$OLD_GOPATH"
    export PS1="$OLD_PS1"
    echo $GOPATH
}

CURDIR=`pwd`
export GOPATH="$CURDIR"
PS1="(`basename $CURDIR`)$PS1"
echo $GOPATH

   
