BROKER_URL = 'redis://:wxtest@localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://:wxtest@localhost:6379/0'

CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT=['json']

CELERY_TASK_RESULT_EXPIRES = 3600
